# NumPy Exercise (5 points)

The homework assignment is due by the end of the day on Thursday, October 2.

Please make sure to solve the assignment problems yourself and obey the university's policies on academic honesty and integrity. Remember that copying and pasting solutions from AI coding assistants, webpages, classmates, or anywhere else is considered plagiarism and academic dishonesty. 

**Note that your solutions are expected to follow the code examples provided in the lecture notes. If your solution to a problem uses functions or codes that are not covered in the lecture notes, that will result in zero marks assigned for that problem.**

To avoid potential conflicts between variable names, it is recommended to restart the kernel often or restart it for every new problem by selecting `Kernel -> Restart Kernel...`. Also, when you have completed all problems and before submitting the notebook, it is recommended to select `Kernel -> Restart Kernel and Run All Cells...` to ensure that all cells execute correctly without errors.

NumPy exercise: 5 points

Total points for Assignment 3: 25 points

## Part 1. Array Construction (2 points)

(1.1) Create a 2x10 array (two rows and ten columns) named `ary1`, consisting of all zeros and using integer numbers as the data type. 

In [1]:
import numpy as np
ary1 = np.zeros((2, 10), dtype=int)

(1.2) Create an array named `ary2` consisting of 10 ones using float numbers as the data type. Next, create an array named `ary3` consisting of 10 threes using integer numbers. Afterward, concatenate the three arrays (ary1, ary2, ary3) horizontally to obtain a 4x10 array named `ary4`.

In [2]:
import numpy as np

ary2 = np.ones(10, dtype=float)
ary3 = np.full(10, 3, dtype=int)
ary4 = np.vstack((ary1, ary2, ary3))

ary4

array([[0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [3., 3., 3., 3., 3., 3., 3., 3., 3., 3.]])

(1.3) Display the data type of `ary4`. Why it is that data type? What can you conclude about concatenating integers and floats in NumPy?

In [5]:
ary4.dtype

# Because NumPy upcasts integers to floats to ensure a common data type that can represent all values.
# Concatenating integers and floats in NumPy always results in a float array.

dtype('float64')

(1.4) Create a numpy array of integers from 10 to 50 using `arange`.

In [6]:
import numpy as np

ary = np.arange(10, 51, dtype=int)

ary

array([10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26,
       27, 28, 29, 30, 31, 32, 33, 34, 35, 36, 37, 38, 39, 40, 41, 42, 43,
       44, 45, 46, 47, 48, 49, 50])

(1.5) Create a numpy array of the "even" integers from 5 to 29.

In [7]:
import numpy as np

arr = np.arange(6, 30, 2)

arr

array([ 6,  8, 10, 12, 14, 16, 18, 20, 22, 24, 26, 28])

(1.6) Create a 3x4 array with values ranging from 0 to 12, using `arange` and `reshape`.

In [8]:
import numpy as np

arr = np.arange(12).reshape(3, 4)

arr

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

## Part 2. Random Number Generators (1 point)

(2.1) Generate an array called `ary5` having 30 random numbers sampled from a normal distribution with mean=15 and standard deviation=2, by applying a Random State to the random number generator. 

In [9]:
import numpy as np

rng = np.random.RandomState(42)
ary5 = rng.normal(15, 2, 30)

ary5

array([15.99342831, 14.7234714 , 16.29537708, 18.04605971, 14.53169325,
       14.53172609, 18.15842563, 16.53486946, 14.06105123, 16.08512009,
       14.07316461, 14.06854049, 15.48392454, 11.17343951, 11.55016433,
       13.87542494, 12.97433776, 15.62849467, 13.18395185, 12.1753926 ,
       17.93129754, 14.5484474 , 15.13505641, 12.15050363, 13.91123455,
       15.22184518, 12.69801285, 15.75139604, 13.79872262, 14.4166125 ])

(2.2) Display the indices of the elements in `ary5` sorted in ascending order. 

In [10]:
sorted_indices = np.argsort(ary5)

sorted_indices

array([13, 14, 23, 19, 26, 16, 18, 28, 15, 24,  8, 11, 10, 29,  4,  5, 21,
        1, 22, 25, 12, 17, 27,  0,  9,  2,  7, 20,  3,  6])

(2.3) Generate a 4x5 array called `ary6` of random numbers sampled from a uniform distribution. Use the random seed `12` to ensure reproducibility. 

In [11]:
import numpy as np

np.random.seed(12)
ary6 = np.random.rand(4, 5)

ary6

array([[0.15416284, 0.7400497 , 0.26331502, 0.53373939, 0.01457496],
       [0.91874701, 0.90071485, 0.03342143, 0.95694934, 0.13720932],
       [0.28382835, 0.60608318, 0.94422514, 0.85273554, 0.00225923],
       [0.52122603, 0.55203763, 0.48537741, 0.76813415, 0.16071675]])

(2.4) Display the average values of the rows of `ary6`.

In [12]:
row_means = ary6.mean(axis=1)

row_means

array([0.34116838, 0.58940839, 0.53782629, 0.4974984 ])

(2.5) Display the index of the minimum element in each column in `ary6`. 

In [13]:
min_indices = np.argmin(ary6, axis=0).astype(np.int64)

print(repr(min_indices))

array([0, 3, 1, 0, 2])


## Part 3. Boolean Masks for Indexing (0.5 points)

(3.1) Create a Boolean mask of the elements in `ary6` that are in the range between 0.3 and 0.8, and afterward use the mask to extract the elements into a new array `ary7`.

In [14]:
import numpy as np

np.random.seed(12)
ary6 = np.random.rand(4, 5)

mask = (ary6 >= 0.3) & (ary6 <= 0.8)

ary7 = ary6[mask]

print(repr(ary7))

array([0.7400497 , 0.53373939, 0.60608318, 0.52122603, 0.55203763,
       0.48537741, 0.76813415])


## Part 4. Reshaping NumPy Arrays (1.5 points)

(4.1) Flatten `ary6` using both `flatten()` and `ravel()` and check if the resulting arrays are views of `ary6` (i.e., whether they share the same memory).

In [15]:
import numpy as np

np.random.seed(12)
ary6 = np.random.rand(4, 5)
print("ary6:\n", ary6)

ary_flatten = ary6.flatten()
print("\nFlatten using flatten():\n", ary_flatten)

ary_ravel = ary6.ravel()
print("\nFlatten using ravel():\n", ary_ravel)

print("\nDoes flatten() result share memory with ary6?", np.shares_memory(ary6, ary_flatten))
print("Does ravel() result share memory with ary6?", np.shares_memory(ary6, ary_ravel))

ary6:
 [[0.15416284 0.7400497  0.26331502 0.53373939 0.01457496]
 [0.91874701 0.90071485 0.03342143 0.95694934 0.13720932]
 [0.28382835 0.60608318 0.94422514 0.85273554 0.00225923]
 [0.52122603 0.55203763 0.48537741 0.76813415 0.16071675]]

Flatten using flatten():
 [0.15416284 0.7400497  0.26331502 0.53373939 0.01457496 0.91874701
 0.90071485 0.03342143 0.95694934 0.13720932 0.28382835 0.60608318
 0.94422514 0.85273554 0.00225923 0.52122603 0.55203763 0.48537741
 0.76813415 0.16071675]

Flatten using ravel():
 [0.15416284 0.7400497  0.26331502 0.53373939 0.01457496 0.91874701
 0.90071485 0.03342143 0.95694934 0.13720932 0.28382835 0.60608318
 0.94422514 0.85273554 0.00225923 0.52122603 0.55203763 0.48537741
 0.76813415 0.16071675]

Does flatten() result share memory with ary6? False
Does ravel() result share memory with ary6? True


(4.2) Create an array of 40 linearly spaced data points between 3 and 5.

In [16]:
import numpy as np

ary = np.linspace(3, 5, 40)

ary

array([3.        , 3.05128205, 3.1025641 , 3.15384615, 3.20512821,
       3.25641026, 3.30769231, 3.35897436, 3.41025641, 3.46153846,
       3.51282051, 3.56410256, 3.61538462, 3.66666667, 3.71794872,
       3.76923077, 3.82051282, 3.87179487, 3.92307692, 3.97435897,
       4.02564103, 4.07692308, 4.12820513, 4.17948718, 4.23076923,
       4.28205128, 4.33333333, 4.38461538, 4.43589744, 4.48717949,
       4.53846154, 4.58974359, 4.64102564, 4.69230769, 4.74358974,
       4.79487179, 4.84615385, 4.8974359 , 4.94871795, 5.        ])

(4.3) For the given array `mat`, in the following cells apply slicing operations to replicate the displayed outputs.

In [17]:
mat = np.arange(1,26).reshape(5,5)
mat

array([[ 1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10],
       [11, 12, 13, 14, 15],
       [16, 17, 18, 19, 20],
       [21, 22, 23, 24, 25]])

In [18]:
import numpy as np

mat = np.arange(1, 26).reshape(5, 5)

result = mat[2:, 1:]

result

array([[12, 13, 14, 15],
       [17, 18, 19, 20],
       [22, 23, 24, 25]])

In [19]:
import numpy as np

mat = np.arange(1, 26).reshape(5, 5)

result = mat[0:3, 1:2]

result

array([[ 2],
       [ 7],
       [12]])

In [21]:
import numpy as np

mat = np.arange(1, 26).reshape(5, 5)

result = mat[1:3, 2:5:2]

result

array([[ 8, 10],
       [13, 15]])

In [28]:
# Your code here

array([[16, 17, 18, 19, 20],
       [21, 22, 23, 24, 25]])